# For details of what checks are run for PRs please refer below
name: .NET Core CI

on: [pull_request, workflow_dispatch]

jobs:
  # Fail if there are build warnings
  #
  # To check for build warnings locally you may need to run a clean build.
  #
  # This can be done by running `dotnet clean` before running `dotnet build`
  build-warnings:
    name: Build warnings check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0'

      - name: Build
        run: dotnet build /WarnAsError
